#define MORFENC_WHITE 1
#define MORFENC_INTERP 6
#define MORFENC_DIGITS 62
#define MORFENC_PSEUDOLETTERS 72
#define MORFENC_LETTERS 74
#define MORFENC_CASEABLE 76
#define MORFENC_NOTACHARCTER 216

#define MORFENC_MAXUNIVAL 8483
